### ISSUE TITLE
Lighting Issue(s)

### ISSUE THREAD

**Issue by Masonrf** [JMY1000/CyclesMineways#8]
I use this script rather often when rendering Minecraft worlds and I have noticed a few lighting issues with the current CyclesMineways script:
I am using Blender 2.77 and CyclesMineways 1.2.2:

Without editing any of the blocks's nodes, the blocks that have light emit light like they should, but the blocks themselves are very dark (which looks kind of crappy):
![lighting-test](https://cloud.githubusercontent.com/assets/16567072/14931819/1cfda26e-0e34-11e6-9b94-ad50339150d3.png)

Editing the "Emission" node and setting the strength to about 20 Seems to give a much better looking result:
![lighting-test-fixed](https://cloud.githubusercontent.com/assets/16567072/14931821/207afc3e-0e34-11e6-8dd6-988742625f0c.png)

Another thing I noticed were that some non-block emitters do not emit light like the blocks do (as seen in above images).  I'm uncertain of a way to fix this, but there is a large difference in the nodes of light emitting blocks and light emitting (or supposed to be at least). The emission strength node that I changed is circled in the below pictures. This is what I was suggesting needed to be changed in the above section.
Difference between Glowstone and Torches:
![glowstone](https://cloud.githubusercontent.com/assets/16567072/14931824/24faee68-0e34-11e6-84c2-1bcada33a996.PNG)
![torch](https://cloud.githubusercontent.com/assets/16567072/14931825/28a00e22-0e34-11e6-8b41-925976f89ef2.PNG)

I'm not sure if any of these things are able to be put into the script or if I just have to do it manually.  Any kind of feedback would be appreciated!
Thanks,
- Masonrf

**Comment by JMY1000** [comment]
That's odd, let me take a look into those. I haven't had the lighting issue before, it could be something introduced recently.

**Comment by JMY1000** [comment]
Still doing some testing, but I'm getting clean renders so far with the default. It could be something with ow your scene is set up. Would you be willing to post it?

**Comment by JMY1000** [comment]
In terms of the second issue, that's because the emission shader was changed and the transparent/emitting shader still uses the old version. I'll update it in the future.

**Comment by Masonrf** [comment]
Heres the .blend, my cyclesmineways script, and .obj files,
[Lighting-Test.zip](https://github.com/JMY1000/CyclesMineways/files/243831/Lighting-Test.zip)

**Comment by JMY1000** [comment]
Not really sure what's happening with yours, after re-importing the OBJ it worked fine. Your individual file had the same issue though.

![http://i.imgur.com/3ldrQlc.png](url)

Anyways, I'm removing the "bug" label since it seems to be specific to you or something you're doing, but I'll keep the enhancement anyways since it needs to be applied to transparent materials anyways.

**Comment by Masonrf** [comment]
Ok, I'll do some testing on my side to see if it's anything I accidentally changed.

Another thing I noticed (though it may be a separate issue idk) is that I can't name a file with spaces or the script does not work at all. I don't know if that's intentional or not. It's also not that big of a deal.

**Comment by Masonrf** [comment]
After I messed around a bit with this in a newer version I think I found why the lighting behaved oddly.  I was using Volume Absorption node to produce a "night" effect.  The side effects is it makes the block faces not show up as they would normally. 

Just thought I'd share this info. I don't know if its fixable or if I should use another method to make night scenes. I'm open for new ways to produce night time lighting if anyone has another method.

**Comment by ThomasLynn** [comment]
@Masonrf  In the real world, the moon doesn't suck up all the light (although I'm sure you could find someone who thought it did, this is the internet, after all). I suggest using more "natural" methods of creating a night scene, like reducing/removing the sun's (or moon's, in night time scenes) light, using the night sky node setup as provided by the script (setting the time to 0.00, not 12.00), and lighting your scene in a "night" kind of way (using glowstone/torches for light, not the sky).

I know I've already posted this image, but I feel like it's relevent:
![villageatnighttwo](https://cloud.githubusercontent.com/assets/11364504/17609256/16601b5a-602b-11e6-9e3c-a229983f52c5.png)
Then I rendered again with volume absorption:
![foggynightvillagerunder](https://cloud.githubusercontent.com/assets/11364504/17609268/33659018-602b-11e6-9192-c0bbdd562a30.png)

unless you're going for a foggy (scary?) night look, the absorption is not needed. It's worth noting that in the second picture, you cannot see the night sky, even though in a real foggy night you might be able to.


(I hope this download works)
[https://www.mediafire.com/?bfi032fqy2b48d9](url)

(novice "art expert" explanation incoming (I'm sure these 5 10 min photography and CG rendering YouTube videos will pay off!))
I've used glowstone and torches (and lava) to feed light into the image.
I've raised up the glowstone using fence, and put the torches above the door so that the light is going down as much as possible (if the light sources were lower, it would illuminate up, which looks weird/creepy to humans).
I haven't used a sun lamp, so no shadows created from the sky's light; the moon typically doesn't give off enough light to cast visible shadows (in areas with light pollution, like a village).

other things I did with this image (non light related)
I set the Fstop to 7 and focused on the torch. This blurs out the glowstone in the forground.
I increased the amount of stars in the sky, as little sky was shown (at the time, the script created much less stars)
The camera is at a "human height" for a "this could be you" kinda feel.

If I were doing this image again, I'd probably move the village farm down a few blocks, maybe using that space for something else, like another light.

**Comment by Masonrf** [comment]
@ThomasLynn Well, yes I know there is natural light at night. I had some ways of setting that up, though that mostly involved keeping the volume absorption density very low and using sky light with a low power sun lamp set to straight down which removed most shadows.  The only reason I ended up using volume absorption is because I couldn't find anything else that worked as well.

"using the night sky node setup as provided by the script (setting the time to 0.00, not 12.00)"
I'll use this. I didn't even realize it was a thing. *facepalm*
Now that I look at it, there's also a bunch of other useful options... I should have read the actual script awhile ago... 

While I'm not too much of a novice the photography aspect of it, I do appreciate the advice. Thanks for the help!

**Comment by ThomasLynn** [comment]
@Masonrf  Huh, it didn't even occur to me that people didn't know about the script settings (Too much time staring at the code, probably :) ), maybe @JMY1000 and I can make a popup to tell people that the script it customisable? Or a more visible GUI for controlling the script, like the script has with changing water shader (under scenes tab after running the script, well hidden, unfortunately).


How does this sound:
Run the script
(the main, texturing part of the current script does not get run)
a popup appears saying "to run the script, please use the GUI set up on the left side of all view-ports"
a GUI shows up with all the settings (a list of all possible PREFIXes, time, shader shader type, and so on)
user pressed "run script" button
the script runs with whatever settings they've set up with the buttons


Would that be more user friendly, do you think? I'm concerned that if we do it that way, the user might not find the GUI buttons, as Blender's GUI is very cluttered. We could have a Boolean in the script to switch between the two types of running the script, but I think whatever the default value for this is will stay that set to the default when a normal user wants to use the script.

**Comment by Masonrf** [comment]
@ThomasLynn yes I do think a popup of some sort would be helpful to most users. I like how you're thinking with the GUI for the settings and I think that would be a great thing to implement. If at all possible though, I think some example pictures or a GIF type thing should be added for settings like water that would show the differences between the settings. Want me to post an issue?

**Comment by ThomasLynn** [comment]
sure, let's talk about GUIs in another thread.
